// This file is auto-generated by Supabase CLI
// It provides TypeScript types for your database tables

export type AwardType = "Offensive MVP" | "Defensive MVP" | "Rookie of Tournament";
export type EventTier = "T1" | "T2" | "T3" | "T4";
export type EventType = "League" | "Tournament";
export type League = 
  | "UPA" 
  | "UPA College" 
  | "WR" 
  | "MPBA" 
  | "Rising Stars" 
  | "Staten Island Basketball Association" 
  | "Hall Of Fame League" 
  | "Dunk League" 
  | "Road to 25K";

export type PlayerPosition = 
  | "Point Guard" 
  | "Shooting Guard" 
  | "Lock" 
  | "Power Forward" 
  | "Center";

export type SalaryTier = "S" | "A" | "B" | "C" | "D";

export type Stage = 
  | "Regular Season" 
  | "Group Play" 
  | "Round 1" 
  | "Round 2" 
  | "Round 3" 
  | "Round 4" 
  | "Semi Finals" 
  | "Finals" 
  | "Grand Finals" 
  | "L1" 
  | "L2" 
  | "L3" 
  | "L4" 
  | "L5" 
  | "W1" 
  | "W2" 
  | "W3" 
  | "W4" 
  | "LF" 
  | "WF";

// Add your table interfaces here based on the generated types
// Example:
/*
export interface Player {
  id: string;
  name: string;
  position: PlayerPosition;
  // ... other fields
}
*/

// Re-export generated types for reference
export * from '../../supabase_types.json.js';

// Add any custom types or utility functions here
